# Generated by Django 3.0.2 on 2020-01-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.RenameField(
            model_name='genretitle',
            old_name='movies',
            new_name='movie',
        ),
    ]
