# Generated by Django 3.0.2 on 2020-01-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_genretitle_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genretitle',
            name='genre',
        ),
        migrations.AddField(
            model_name='genretitle',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='watch.Genre'),
        ),
    ]
