# Generated by Django 3.0.2 on 2020-01-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_auto_20200125_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='watch.Genre'),
        ),
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
